#ifndef __S2_APAD_MENU_CONTROL_V9__AES__H__
#define __S2_APAD_MENU_CONTROL_V9__AES__H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_APAD_Menu_Control_v9__AES__ROOMONFB_DIG_INPUT 0
#define __S2_APAD_Menu_Control_v9__AES__EXITSOURCECONTROL_DIG_INPUT 1
#define __S2_APAD_Menu_Control_v9__AES__CYCLEROOMSOURCE_DIG_INPUT 2
#define __S2_APAD_Menu_Control_v9__AES__EXITTOOLS_DIG_INPUT 3
#define __S2_APAD_Menu_Control_v9__AES__EXITSOURCESETUP_DIG_INPUT 4
#define __S2_APAD_Menu_Control_v9__AES__DEFAULTROOMONFB_DIG_INPUT 5
#define __S2_APAD_Menu_Control_v9__AES__ROOMCONNECTED_DIG_INPUT 6
#define __S2_APAD_Menu_Control_v9__AES__SYSTEMBUILDER_DIG_INPUT 7
#define __S2_APAD_Menu_Control_v9__AES__HOUSEMENUENABLED_DIG_INPUT 8
#define __S2_APAD_Menu_Control_v9__AES__EXITHOUSEMENU_DIG_INPUT 9
#define __S2_APAD_Menu_Control_v9__AES__SYSTEMINITIALIZED_DIG_INPUT 10
#define __S2_APAD_Menu_Control_v9__AES__ALLSOURCESDISABLED_DIG_INPUT 11
#define __S2_APAD_Menu_Control_v9__AES__INTERRUPTACTIVE_DIG_INPUT 12
#define __S2_APAD_Menu_Control_v9__AES__ENABLEDONOTDISTURBBUTTON_DIG_INPUT 13
#define __S2_APAD_Menu_Control_v9__AES__ENABLESLEEPBUTTON_DIG_INPUT 14
#define __S2_APAD_Menu_Control_v9__AES__SLEEPWARNING_DIG_INPUT 15
#define __S2_APAD_Menu_Control_v9__AES__PRIORITYMODECONTROLOK_DIG_INPUT 16
#define __S2_APAD_Menu_Control_v9__AES__PRIORITYMODECONTROLFAILED_DIG_INPUT 17
#define __S2_APAD_Menu_Control_v9__AES__PRIORITYMODECONTROLREMOVED_DIG_INPUT 18
#define __S2_APAD_Menu_Control_v9__AES__POWER_DIG_INPUT 19
#define __S2_APAD_Menu_Control_v9__AES__ENTER_DIG_INPUT 20
#define __S2_APAD_Menu_Control_v9__AES__KNOBLEFT_DIG_INPUT 21
#define __S2_APAD_Menu_Control_v9__AES__KNOBRIGHT_DIG_INPUT 22
#define __S2_APAD_Menu_Control_v9__AES__SOFTBUTTON3HELD_DIG_INPUT 23
#define __S2_APAD_Menu_Control_v9__AES__SOFTBUTTON2HELD_DIG_INPUT 24

#define __S2_APAD_Menu_Control_v9__AES__SOFTKEY_DIG_INPUT 25
#define __S2_APAD_Menu_Control_v9__AES__SOFTKEY_ARRAY_LENGTH 4
#define __S2_APAD_Menu_Control_v9__AES__GROUPACTIVE_DIG_INPUT 29
#define __S2_APAD_Menu_Control_v9__AES__GROUPACTIVE_ARRAY_LENGTH 6
#define __S2_APAD_Menu_Control_v9__AES__GROUPDISABLED_DIG_INPUT 35
#define __S2_APAD_Menu_Control_v9__AES__GROUPDISABLED_ARRAY_LENGTH 6
#define __S2_APAD_Menu_Control_v9__AES__SOURCEDISABLED_DIG_INPUT 41
#define __S2_APAD_Menu_Control_v9__AES__SOURCEDISABLED_ARRAY_LENGTH 10

/*
* ANALOG_INPUT
*/
#define __S2_APAD_Menu_Control_v9__AES__TOTALROOMENTRIES_ANALOG_INPUT 0
#define __S2_APAD_Menu_Control_v9__AES__DEFAULTROOM_ANALOG_INPUT 1
#define __S2_APAD_Menu_Control_v9__AES__DRIVENROOMNUMBER_ANALOG_INPUT 2
#define __S2_APAD_Menu_Control_v9__AES__CURRENTSOURCE_ANALOG_INPUT 3
#define __S2_APAD_Menu_Control_v9__AES__CURRENTSLEEPTIME_ANALOG_INPUT 4
#define __S2_APAD_Menu_Control_v9__AES__NEWSLEEPTIME_ANALOG_INPUT 5
#define __S2_APAD_Menu_Control_v9__AES__PRIORITYMODE_ANALOG_INPUT 6

#define __S2_APAD_Menu_Control_v9__AES__EXTERNALSOURCENAME$_STRING_INPUT 7
#define __S2_APAD_Menu_Control_v9__AES__EXTERNALSOURCENAME$_STRING_MAX_LEN 24
CREATE_STRING_STRUCT( S2_APAD_Menu_Control_v9__AES_, __EXTERNALSOURCENAME$, __S2_APAD_Menu_Control_v9__AES__EXTERNALSOURCENAME$_STRING_MAX_LEN );
#define __S2_APAD_Menu_Control_v9__AES__INTERRUPTMESSAGE$_STRING_INPUT 8
#define __S2_APAD_Menu_Control_v9__AES__INTERRUPTMESSAGE$_STRING_MAX_LEN 100
CREATE_STRING_STRUCT( S2_APAD_Menu_Control_v9__AES_, __INTERRUPTMESSAGE$, __S2_APAD_Menu_Control_v9__AES__INTERRUPTMESSAGE$_STRING_MAX_LEN );


#define __S2_APAD_Menu_Control_v9__AES__ROOMEQUIPMENTID_ANALOG_INPUT 9
#define __S2_APAD_Menu_Control_v9__AES__ROOMEQUIPMENTID_ARRAY_LENGTH 24
#define __S2_APAD_Menu_Control_v9__AES__SOURCEDEVICETYPE_ANALOG_INPUT 33
#define __S2_APAD_Menu_Control_v9__AES__SOURCEDEVICETYPE_ARRAY_LENGTH 10
#define __S2_APAD_Menu_Control_v9__AES__SOURCEOWNER_ANALOG_INPUT 43
#define __S2_APAD_Menu_Control_v9__AES__SOURCEOWNER_ARRAY_LENGTH 10
#define __S2_APAD_Menu_Control_v9__AES__LISTPOSITION_ANALOG_INPUT 93
#define __S2_APAD_Menu_Control_v9__AES__LISTPOSITION_ARRAY_LENGTH 10
#define __S2_APAD_Menu_Control_v9__AES__ROOMNAMES$_STRING_INPUT 53
#define __S2_APAD_Menu_Control_v9__AES__ROOMNAMES$_ARRAY_NUM_ELEMS 24
#define __S2_APAD_Menu_Control_v9__AES__ROOMNAMES$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_APAD_Menu_Control_v9__AES_, __ROOMNAMES$, __S2_APAD_Menu_Control_v9__AES__ROOMNAMES$_ARRAY_NUM_ELEMS, __S2_APAD_Menu_Control_v9__AES__ROOMNAMES$_ARRAY_NUM_CHARS );
#define __S2_APAD_Menu_Control_v9__AES__GROUPNAMES$_STRING_INPUT 77
#define __S2_APAD_Menu_Control_v9__AES__GROUPNAMES$_ARRAY_NUM_ELEMS 6
#define __S2_APAD_Menu_Control_v9__AES__GROUPNAMES$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_APAD_Menu_Control_v9__AES_, __GROUPNAMES$, __S2_APAD_Menu_Control_v9__AES__GROUPNAMES$_ARRAY_NUM_ELEMS, __S2_APAD_Menu_Control_v9__AES__GROUPNAMES$_ARRAY_NUM_CHARS );
#define __S2_APAD_Menu_Control_v9__AES__SOURCENAMES$_STRING_INPUT 83
#define __S2_APAD_Menu_Control_v9__AES__SOURCENAMES$_ARRAY_NUM_ELEMS 10
#define __S2_APAD_Menu_Control_v9__AES__SOURCENAMES$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_APAD_Menu_Control_v9__AES_, __SOURCENAMES$, __S2_APAD_Menu_Control_v9__AES__SOURCENAMES$_ARRAY_NUM_ELEMS, __S2_APAD_Menu_Control_v9__AES__SOURCENAMES$_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/
#define __S2_APAD_Menu_Control_v9__AES__ROOMCONNECT_DIG_OUTPUT 0
#define __S2_APAD_Menu_Control_v9__AES__ROOMDISCONNECT_DIG_OUTPUT 1
#define __S2_APAD_Menu_Control_v9__AES__ROOMON_DIG_OUTPUT 2
#define __S2_APAD_Menu_Control_v9__AES__ROOMOFF_DIG_OUTPUT 3
#define __S2_APAD_Menu_Control_v9__AES__SOURCECONNECT_DIG_OUTPUT 4
#define __S2_APAD_Menu_Control_v9__AES__SOURCEDISCONNECT_DIG_OUTPUT 5
#define __S2_APAD_Menu_Control_v9__AES__CONTROLLINGFOREIGNROOM_DIG_OUTPUT 6
#define __S2_APAD_Menu_Control_v9__AES__DEFAULTROOMOFF_DIG_OUTPUT 7
#define __S2_APAD_Menu_Control_v9__AES__SHOWINTERRUPTSUBPAGE_DIG_OUTPUT 8

#define __S2_APAD_Menu_Control_v9__AES__DIGITALOUT_DIG_OUTPUT 9
#define __S2_APAD_Menu_Control_v9__AES__DIGITALOUT_ARRAY_LENGTH 6
#define __S2_APAD_Menu_Control_v9__AES__GROUPON_DIG_OUTPUT 15
#define __S2_APAD_Menu_Control_v9__AES__GROUPON_ARRAY_LENGTH 6
#define __S2_APAD_Menu_Control_v9__AES__GROUPOFF_DIG_OUTPUT 21
#define __S2_APAD_Menu_Control_v9__AES__GROUPOFF_ARRAY_LENGTH 6

/*
* ANALOG_OUTPUT
*/
#define __S2_APAD_Menu_Control_v9__AES__CURRENTPAGE_ANALOG_OUTPUT 0
#define __S2_APAD_Menu_Control_v9__AES__CURRENTSUBPAGE_ANALOG_OUTPUT 1
#define __S2_APAD_Menu_Control_v9__AES__ROOMEQUIPMENTIDSELECTED_ANALOG_OUTPUT 2
#define __S2_APAD_Menu_Control_v9__AES__NOWPLAYINGINDEX_ANALOG_OUTPUT 3
#define __S2_APAD_Menu_Control_v9__AES__SOURCEGUIIDSELECTED_ANALOG_OUTPUT 4
#define __S2_APAD_Menu_Control_v9__AES__SOURCEEQUIPMENTIDSELECTED_ANALOG_OUTPUT 5
#define __S2_APAD_Menu_Control_v9__AES__NEWSOURCEREQUESTED_ANALOG_OUTPUT 6
#define __S2_APAD_Menu_Control_v9__AES__SCROLLBAR_ANALOG_OUTPUT 7
#define __S2_APAD_Menu_Control_v9__AES__NEWSLEEPTIMEOUT_ANALOG_OUTPUT 8
#define __S2_APAD_Menu_Control_v9__AES__PRIORITYMODESOURCECONTROLREQUESTED_ANALOG_OUTPUT 9
#define __S2_APAD_Menu_Control_v9__AES__PRIORITYMODESOURCECONTROLOVERRIDE_ANALOG_OUTPUT 10

#define __S2_APAD_Menu_Control_v9__AES__CURRENTSOURCE$_STRING_OUTPUT 11

#define __S2_APAD_Menu_Control_v9__AES__SOFTKEY$_STRING_OUTPUT 12
#define __S2_APAD_Menu_Control_v9__AES__SOFTKEY$_ARRAY_LENGTH 4
#define __S2_APAD_Menu_Control_v9__AES__SERIALOUT$_STRING_OUTPUT 16
#define __S2_APAD_Menu_Control_v9__AES__SERIALOUT$_ARRAY_LENGTH 5

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/
CREATE_INTARRAY1D( S2_APAD_Menu_Control_v9__AES_, __OTHERINDEX, 6 );;
CREATE_INTARRAY1D( S2_APAD_Menu_Control_v9__AES_, __SOURCEREORDERARRAY, 10 );;


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_APAD_Menu_Control_v9__AES__CURRENTSOURCEINT$_STRING_MAX_LEN 24
CREATE_STRING_STRUCT( S2_APAD_Menu_Control_v9__AES_, __CURRENTSOURCEINT$, __S2_APAD_Menu_Control_v9__AES__CURRENTSOURCEINT$_STRING_MAX_LEN );
#define __S2_APAD_Menu_Control_v9__AES__OTHERMENU$_ARRAY_NUM_ELEMS 6
#define __S2_APAD_Menu_Control_v9__AES__OTHERMENU$_ARRAY_NUM_CHARS 8
CREATE_STRING_ARRAY( S2_APAD_Menu_Control_v9__AES_, __OTHERMENU$, __S2_APAD_Menu_Control_v9__AES__OTHERMENU$_ARRAY_NUM_ELEMS, __S2_APAD_Menu_Control_v9__AES__OTHERMENU$_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_APAD_Menu_Control_v9__AES_ )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __SOFTKEY );
   DECLARE_IO_ARRAY( __GROUPACTIVE );
   DECLARE_IO_ARRAY( __GROUPDISABLED );
   DECLARE_IO_ARRAY( __SOURCEDISABLED );
   DECLARE_IO_ARRAY( __DIGITALOUT );
   DECLARE_IO_ARRAY( __GROUPON );
   DECLARE_IO_ARRAY( __GROUPOFF );
   DECLARE_IO_ARRAY( __ROOMEQUIPMENTID );
   DECLARE_IO_ARRAY( __SOURCEDEVICETYPE );
   DECLARE_IO_ARRAY( __SOURCEOWNER );
   DECLARE_IO_ARRAY( __LISTPOSITION );
   DECLARE_IO_ARRAY( __SOFTKEY$ );
   DECLARE_IO_ARRAY( __SERIALOUT$ );
   unsigned short __CURRENTROOM;
   unsigned short __SOURCESEMAPHORE;
   unsigned short __CURRENTSOURCECONTROLLABLE;
   unsigned short __LASTSOURCEREQUESTED;
   unsigned short __PREVIEWSOURCE;
   unsigned short __PREVIEWROOM;
   unsigned short __SCROLLINDEX;
   unsigned short __SCROLLHIGHLIGHT;
   unsigned short __SCROLLMAX;
   unsigned short __CURRENTMESSAGE;
   unsigned short __PREVIOUSPAGE;
   unsigned short __PAGEOTHERINDEX;
   unsigned short __SOURCESELECTCALLINGPAGE;
   unsigned short __TOTALOTHERENTRIES;
   unsigned short __WAITINGFORSOURCECONTROL;
   unsigned short __LASTUSEDLISTPOSITION;
   DECLARE_INTARRAY( S2_APAD_Menu_Control_v9__AES_, __OTHERINDEX );
   DECLARE_INTARRAY( S2_APAD_Menu_Control_v9__AES_, __SOURCEREORDERARRAY );
   DECLARE_STRING_STRUCT( S2_APAD_Menu_Control_v9__AES_, __CURRENTSOURCEINT$ );
   DECLARE_STRING_ARRAY( S2_APAD_Menu_Control_v9__AES_, __OTHERMENU$ );
   DECLARE_STRING_STRUCT( S2_APAD_Menu_Control_v9__AES_, __EXTERNALSOURCENAME$ );
   DECLARE_STRING_STRUCT( S2_APAD_Menu_Control_v9__AES_, __INTERRUPTMESSAGE$ );
   DECLARE_STRING_ARRAY( S2_APAD_Menu_Control_v9__AES_, __ROOMNAMES$ );
   DECLARE_STRING_ARRAY( S2_APAD_Menu_Control_v9__AES_, __GROUPNAMES$ );
   DECLARE_STRING_ARRAY( S2_APAD_Menu_Control_v9__AES_, __SOURCENAMES$ );
};

START_NVRAM_VAR_STRUCT( S2_APAD_Menu_Control_v9__AES_ )
{
};

DEFINE_WAITEVENT( S2_APAD_Menu_Control_v9__AES_, GROUPNOTVALIDWAIT );
DEFINE_WAITEVENT( S2_APAD_Menu_Control_v9__AES_, SOURCESELECTWAIT );
DEFINE_WAITEVENT( S2_APAD_Menu_Control_v9__AES_, ROOMSELECTWAIT );
DEFINE_WAITEVENT( S2_APAD_Menu_Control_v9__AES_, SOURCECONTROLWAIT );


#endif //__S2_APAD_MENU_CONTROL_V9__AES__H__

