#ifndef __S2_AMFM_LARGE_TP_GUI_PROCESSOR_V1_0_2_H__
#define __S2_AMFM_LARGE_TP_GUI_PROCESSOR_V1_0_2_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLPRESETS_DIG_INPUT 0
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_PAGEUP_DIG_INPUT 1
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_PAGEDOWN_DIG_INPUT 2
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_PAGEFIRST_DIG_INPUT 3
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_PAGELAST_DIG_INPUT 4
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_LINEUP_DIG_INPUT 5
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_LINEDOWN_DIG_INPUT 6
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SELECTLINE_DIG_INPUT 7
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_AMACTIVE_DIG_INPUT 8
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_FMACTIVE_DIG_INPUT 9
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_FMIACTIVE_DIG_INPUT 10


/*
* ANALOG_INPUT
*/
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SELECTEDLINE_ANALOG_INPUT 0
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_MODULEID_ANALOG_INPUT 1
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLPAGESIZE_ANALOG_INPUT 2
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_PRESETTOSAVE_ANALOG_INPUT 3
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_PRESETTOCLEAR_ANALOG_INPUT 4
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_KEYPADAMCHANNELREQUESTED_ANALOG_INPUT 5
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_KEYPADFMCHANNELREQUESTED_ANALOG_INPUT 6


#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_GUIDEINFO$_BUFFER_INPUT 7
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_GUIDEINFO$_BUFFER_MAX_LEN 500
CREATE_STRING_STRUCT( S2_AMFM_Large_TP_GUI_Processor_v1_0_2, __GUIDEINFO$, __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_GUIDEINFO$_BUFFER_MAX_LEN );


/*
* DIGITAL_OUTPUT
*/
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_CHANNELSELECTED_DIG_OUTPUT 0

#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLHIGHLIGHTFB_DIG_OUTPUT 1
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLHIGHLIGHTFB_ARRAY_LENGTH 5

/*
* ANALOG_OUTPUT
*/
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLBAR_ANALOG_OUTPUT 1

#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLINFOREQUEST$_STRING_OUTPUT 0

#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLLISTCHANNELNUMBER_ANALOG_OUTPUT 2
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLLISTCHANNELNUMBER_ARRAY_LENGTH 20
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLLISTINDEXOUT_ANALOG_OUTPUT 22
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLLISTINDEXOUT_ARRAY_LENGTH 20
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLLISTCHANNELNUMBER$_STRING_OUTPUT 42
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLLISTCHANNELNUMBER$_ARRAY_LENGTH 20
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLLISTINDEX$_STRING_OUTPUT 62
#define __S2_AMFM_Large_TP_GUI_Processor_v1_0_2_SCROLLLISTINDEX$_ARRAY_LENGTH 20

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/
CREATE_INTARRAY1D( S2_AMFM_Large_TP_GUI_Processor_v1_0_2, __SCROLLLISTINDEX, 20 );;
CREATE_INTARRAY1D( S2_AMFM_Large_TP_GUI_Processor_v1_0_2, __SCROLLLISTSTATUS, 20 );;


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_AMFM_Large_TP_GUI_Processor_v1_0_2 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __SCROLLHIGHLIGHTFB );
   DECLARE_IO_ARRAY( __SCROLLLISTCHANNELNUMBER );
   DECLARE_IO_ARRAY( __SCROLLLISTINDEXOUT );
   DECLARE_IO_ARRAY( __SCROLLLISTCHANNELNUMBER$ );
   DECLARE_IO_ARRAY( __SCROLLLISTINDEX$ );
   unsigned short __SEMAPHORE;
   unsigned short __SCROLLMODE;
   unsigned short __SCROLLINDEX;
   unsigned short __SCROLLMAX;
   unsigned short __LASTSCROLLINDEX;
   unsigned short __HIGHLIGHTEDITEM;
   unsigned short __HIGHLIGHT;
   DECLARE_INTARRAY( S2_AMFM_Large_TP_GUI_Processor_v1_0_2, __SCROLLLISTINDEX );
   DECLARE_INTARRAY( S2_AMFM_Large_TP_GUI_Processor_v1_0_2, __SCROLLLISTSTATUS );
   DECLARE_STRING_STRUCT( S2_AMFM_Large_TP_GUI_Processor_v1_0_2, __GUIDEINFO$ );
};

START_NVRAM_VAR_STRUCT( S2_AMFM_Large_TP_GUI_Processor_v1_0_2 )
{
};



#endif //__S2_AMFM_LARGE_TP_GUI_PROCESSOR_V1_0_2_H__

