#ifndef __S2_APAD_PL_H__
#define __S2_APAD_PL_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_APAD_PL_ROOMONFB_DIG_INPUT 0
#define __S2_APAD_PL_EXITSOURCECONTROL_DIG_INPUT 1
#define __S2_APAD_PL_CYCLEROOMSOURCE_DIG_INPUT 2
#define __S2_APAD_PL_EXITTOOLS_DIG_INPUT 3
#define __S2_APAD_PL_EXITSOURCESETUP_DIG_INPUT 4
#define __S2_APAD_PL_DEFAULTROOMONFB_DIG_INPUT 5
#define __S2_APAD_PL_ROOMCONNECTED_DIG_INPUT 6
#define __S2_APAD_PL_SYSTEMBUILDER_DIG_INPUT 7
#define __S2_APAD_PL_HOUSEMENUENABLED_DIG_INPUT 8
#define __S2_APAD_PL_EXITHOUSEMENU_DIG_INPUT 9
#define __S2_APAD_PL_SYSTEMINITIALIZED_DIG_INPUT 10
#define __S2_APAD_PL_ALLSOURCESDISABLED_DIG_INPUT 11
#define __S2_APAD_PL_INTERRUPTACTIVE_DIG_INPUT 12
#define __S2_APAD_PL_ENABLEDONOTDISTURBBUTTON_DIG_INPUT 13
#define __S2_APAD_PL_ENABLESLEEPBUTTON_DIG_INPUT 14
#define __S2_APAD_PL_SLEEPWARNING_DIG_INPUT 15
#define __S2_APAD_PL_PRIORITYMODECONTROLOK_DIG_INPUT 16
#define __S2_APAD_PL_PRIORITYMODECONTROLFAILED_DIG_INPUT 17
#define __S2_APAD_PL_PRIORITYMODECONTROLREMOVED_DIG_INPUT 18
#define __S2_APAD_PL_PSTACTIVE_DIG_INPUT 19
#define __S2_APAD_PL_POWER_DIG_INPUT 20
#define __S2_APAD_PL_ENTER_DIG_INPUT 21
#define __S2_APAD_PL_KNOBLEFT_DIG_INPUT 22
#define __S2_APAD_PL_KNOBRIGHT_DIG_INPUT 23
#define __S2_APAD_PL_SOFTBUTTON3HELD_DIG_INPUT 24
#define __S2_APAD_PL_SOFTBUTTON2HELD_DIG_INPUT 25

#define __S2_APAD_PL_SOFTKEY_DIG_INPUT 26
#define __S2_APAD_PL_SOFTKEY_ARRAY_LENGTH 4
#define __S2_APAD_PL_GROUPACTIVE_DIG_INPUT 30
#define __S2_APAD_PL_GROUPACTIVE_ARRAY_LENGTH 6
#define __S2_APAD_PL_GROUPDISABLED_DIG_INPUT 36
#define __S2_APAD_PL_GROUPDISABLED_ARRAY_LENGTH 6
#define __S2_APAD_PL_SOURCEDISABLED_DIG_INPUT 42
#define __S2_APAD_PL_SOURCEDISABLED_ARRAY_LENGTH 11
#define __S2_APAD_PL_ROOMDISABLED_DIG_INPUT 53
#define __S2_APAD_PL_ROOMDISABLED_ARRAY_LENGTH 24

/*
* ANALOG_INPUT
*/
#define __S2_APAD_PL_TOTALROOMENTRIES_ANALOG_INPUT 0
#define __S2_APAD_PL_DEFAULTROOM_ANALOG_INPUT 1
#define __S2_APAD_PL_DRIVENROOMNUMBER_ANALOG_INPUT 2
#define __S2_APAD_PL_CURRENTSOURCE_ANALOG_INPUT 3
#define __S2_APAD_PL_CURRENTSLEEPTIME_ANALOG_INPUT 4
#define __S2_APAD_PL_NEWSLEEPTIME_ANALOG_INPUT 5
#define __S2_APAD_PL_PRIORITYMODE_ANALOG_INPUT 6
#define __S2_APAD_PL_THEATERAUDIOINPUT_ANALOG_INPUT 7

#define __S2_APAD_PL_EXTERNALSOURCENAME$_STRING_INPUT 8
#define __S2_APAD_PL_EXTERNALSOURCENAME$_STRING_MAX_LEN 24
CREATE_STRING_STRUCT( S2_APAD_PL, __EXTERNALSOURCENAME$, __S2_APAD_PL_EXTERNALSOURCENAME$_STRING_MAX_LEN );
#define __S2_APAD_PL_INTERRUPTMESSAGE$_STRING_INPUT 9
#define __S2_APAD_PL_INTERRUPTMESSAGE$_STRING_MAX_LEN 100
CREATE_STRING_STRUCT( S2_APAD_PL, __INTERRUPTMESSAGE$, __S2_APAD_PL_INTERRUPTMESSAGE$_STRING_MAX_LEN );


#define __S2_APAD_PL_ROOMEQUIPMENTID_ANALOG_INPUT 10
#define __S2_APAD_PL_ROOMEQUIPMENTID_ARRAY_LENGTH 24
#define __S2_APAD_PL_SOURCEDEVICETYPE_ANALOG_INPUT 34
#define __S2_APAD_PL_SOURCEDEVICETYPE_ARRAY_LENGTH 11
#define __S2_APAD_PL_SOURCEOWNER_ANALOG_INPUT 45
#define __S2_APAD_PL_SOURCEOWNER_ARRAY_LENGTH 11
#define __S2_APAD_PL_LISTPOSITION_ANALOG_INPUT 98
#define __S2_APAD_PL_LISTPOSITION_ARRAY_LENGTH 11
#define __S2_APAD_PL_ROOMNAMES$_STRING_INPUT 56
#define __S2_APAD_PL_ROOMNAMES$_ARRAY_NUM_ELEMS 25
#define __S2_APAD_PL_ROOMNAMES$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_APAD_PL, __ROOMNAMES$, __S2_APAD_PL_ROOMNAMES$_ARRAY_NUM_ELEMS, __S2_APAD_PL_ROOMNAMES$_ARRAY_NUM_CHARS );
#define __S2_APAD_PL_GROUPNAMES$_STRING_INPUT 81
#define __S2_APAD_PL_GROUPNAMES$_ARRAY_NUM_ELEMS 6
#define __S2_APAD_PL_GROUPNAMES$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_APAD_PL, __GROUPNAMES$, __S2_APAD_PL_GROUPNAMES$_ARRAY_NUM_ELEMS, __S2_APAD_PL_GROUPNAMES$_ARRAY_NUM_CHARS );
#define __S2_APAD_PL_SOURCENAMES$_STRING_INPUT 87
#define __S2_APAD_PL_SOURCENAMES$_ARRAY_NUM_ELEMS 11
#define __S2_APAD_PL_SOURCENAMES$_ARRAY_NUM_CHARS 24
CREATE_STRING_ARRAY( S2_APAD_PL, __SOURCENAMES$, __S2_APAD_PL_SOURCENAMES$_ARRAY_NUM_ELEMS, __S2_APAD_PL_SOURCENAMES$_ARRAY_NUM_CHARS );

/*
* DIGITAL_OUTPUT
*/
#define __S2_APAD_PL_ROOMCONNECT_DIG_OUTPUT 0
#define __S2_APAD_PL_ROOMDISCONNECT_DIG_OUTPUT 1
#define __S2_APAD_PL_ROOMON_DIG_OUTPUT 2
#define __S2_APAD_PL_ROOMOFF_DIG_OUTPUT 3
#define __S2_APAD_PL_SOURCECONNECT_DIG_OUTPUT 4
#define __S2_APAD_PL_SOURCEDISCONNECT_DIG_OUTPUT 5
#define __S2_APAD_PL_CONTROLLINGFOREIGNROOM_DIG_OUTPUT 6
#define __S2_APAD_PL_DEFAULTROOMOFF_DIG_OUTPUT 7
#define __S2_APAD_PL_SHOWINTERRUPTSUBPAGE_DIG_OUTPUT 8

#define __S2_APAD_PL_DIGITALOUT_DIG_OUTPUT 9
#define __S2_APAD_PL_DIGITALOUT_ARRAY_LENGTH 6
#define __S2_APAD_PL_GROUPON_DIG_OUTPUT 15
#define __S2_APAD_PL_GROUPON_ARRAY_LENGTH 6
#define __S2_APAD_PL_GROUPOFF_DIG_OUTPUT 21
#define __S2_APAD_PL_GROUPOFF_ARRAY_LENGTH 6

/*
* ANALOG_OUTPUT
*/
#define __S2_APAD_PL_CURRENTPAGE_ANALOG_OUTPUT 0
#define __S2_APAD_PL_CURRENTSUBPAGE_ANALOG_OUTPUT 1
#define __S2_APAD_PL_ROOMEQUIPMENTIDSELECTED_ANALOG_OUTPUT 2
#define __S2_APAD_PL_NOWPLAYINGINDEX_ANALOG_OUTPUT 3
#define __S2_APAD_PL_SOURCEGUIIDSELECTED_ANALOG_OUTPUT 4
#define __S2_APAD_PL_SOURCEEQUIPMENTIDSELECTED_ANALOG_OUTPUT 5
#define __S2_APAD_PL_NEWSOURCEREQUESTED_ANALOG_OUTPUT 6
#define __S2_APAD_PL_SCROLLBAR_ANALOG_OUTPUT 7
#define __S2_APAD_PL_NEWSLEEPTIMEOUT_ANALOG_OUTPUT 8
#define __S2_APAD_PL_PRIORITYMODESOURCECONTROLREQUESTED_ANALOG_OUTPUT 9
#define __S2_APAD_PL_PRIORITYMODESOURCECONTROLOVERRIDE_ANALOG_OUTPUT 10

#define __S2_APAD_PL_CURRENTSOURCE$_STRING_OUTPUT 11

#define __S2_APAD_PL_SOFTKEY$_STRING_OUTPUT 12
#define __S2_APAD_PL_SOFTKEY$_ARRAY_LENGTH 4
#define __S2_APAD_PL_SERIALOUT$_STRING_OUTPUT 16
#define __S2_APAD_PL_SERIALOUT$_ARRAY_LENGTH 5

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/
CREATE_INTARRAY1D( S2_APAD_PL, __OTHERINDEX, 6 );;
CREATE_INTARRAY1D( S2_APAD_PL, __SOURCEREORDERARRAY, 11 );;


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_APAD_PL_CURRENTSOURCEINT$_STRING_MAX_LEN 24
CREATE_STRING_STRUCT( S2_APAD_PL, __CURRENTSOURCEINT$, __S2_APAD_PL_CURRENTSOURCEINT$_STRING_MAX_LEN );
#define __S2_APAD_PL_OTHERMENU$_ARRAY_NUM_ELEMS 6
#define __S2_APAD_PL_OTHERMENU$_ARRAY_NUM_CHARS 8
CREATE_STRING_ARRAY( S2_APAD_PL, __OTHERMENU$, __S2_APAD_PL_OTHERMENU$_ARRAY_NUM_ELEMS, __S2_APAD_PL_OTHERMENU$_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_APAD_PL )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __SOFTKEY );
   DECLARE_IO_ARRAY( __GROUPACTIVE );
   DECLARE_IO_ARRAY( __GROUPDISABLED );
   DECLARE_IO_ARRAY( __SOURCEDISABLED );
   DECLARE_IO_ARRAY( __ROOMDISABLED );
   DECLARE_IO_ARRAY( __DIGITALOUT );
   DECLARE_IO_ARRAY( __GROUPON );
   DECLARE_IO_ARRAY( __GROUPOFF );
   DECLARE_IO_ARRAY( __ROOMEQUIPMENTID );
   DECLARE_IO_ARRAY( __SOURCEDEVICETYPE );
   DECLARE_IO_ARRAY( __SOURCEOWNER );
   DECLARE_IO_ARRAY( __LISTPOSITION );
   DECLARE_IO_ARRAY( __SOFTKEY$ );
   DECLARE_IO_ARRAY( __SERIALOUT$ );
   unsigned short __CURRENTROOM;
   unsigned short __SOURCESEMAPHORE;
   unsigned short __CURRENTSOURCECONTROLLABLE;
   unsigned short __LASTSOURCEREQUESTED;
   unsigned short __PREVIEWSOURCE;
   unsigned short __PREVIEWROOM;
   unsigned short __SCROLLINDEX;
   unsigned short __SCROLLHIGHLIGHT;
   unsigned short __SCROLLMAX;
   unsigned short __CURRENTMESSAGE;
   unsigned short __PREVIOUSPAGE;
   unsigned short __PAGEOTHERINDEX;
   unsigned short __SOURCESELECTCALLINGPAGE;
   unsigned short __TOTALOTHERENTRIES;
   unsigned short __WAITINGFORSOURCECONTROL;
   unsigned short __LASTUSEDLISTPOSITION;
   DECLARE_INTARRAY( S2_APAD_PL, __OTHERINDEX );
   DECLARE_INTARRAY( S2_APAD_PL, __SOURCEREORDERARRAY );
   DECLARE_STRING_STRUCT( S2_APAD_PL, __CURRENTSOURCEINT$ );
   DECLARE_STRING_ARRAY( S2_APAD_PL, __OTHERMENU$ );
   DECLARE_STRING_STRUCT( S2_APAD_PL, __EXTERNALSOURCENAME$ );
   DECLARE_STRING_STRUCT( S2_APAD_PL, __INTERRUPTMESSAGE$ );
   DECLARE_STRING_ARRAY( S2_APAD_PL, __ROOMNAMES$ );
   DECLARE_STRING_ARRAY( S2_APAD_PL, __GROUPNAMES$ );
   DECLARE_STRING_ARRAY( S2_APAD_PL, __SOURCENAMES$ );
};

START_NVRAM_VAR_STRUCT( S2_APAD_PL )
{
};

DEFINE_WAITEVENT( S2_APAD_PL, GROUPNOTVALIDWAIT );
DEFINE_WAITEVENT( S2_APAD_PL, SOURCESELECTWAIT );
DEFINE_WAITEVENT( S2_APAD_PL, ROOMSELECTWAIT );
DEFINE_WAITEVENT( S2_APAD_PL, SOURCECONTROLWAIT );


#endif //__S2_APAD_PL_H__

