#ifndef __S2_AMFM_GUIDE_ENGINE_V1_0_0_H__
#define __S2_AMFM_GUIDE_ENGINE_V1_0_0_H__




/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_AMFM_Guide_Engine_v1_0_0_AFCAMFMACTIVE_DIG_INPUT 0
#define __S2_AMFM_Guide_Engine_v1_0_0_AMACTIVE_DIG_INPUT 1
#define __S2_AMFM_Guide_Engine_v1_0_0_FMACTIVE_DIG_INPUT 2
#define __S2_AMFM_Guide_Engine_v1_0_0_AMPRESETSAVEFB_DIG_INPUT 3
#define __S2_AMFM_Guide_Engine_v1_0_0_FMPRESETSAVEFB_DIG_INPUT 4


/*
* ANALOG_INPUT
*/
#define __S2_AMFM_Guide_Engine_v1_0_0_AMPRESETMODEFB_ANALOG_INPUT 0
#define __S2_AMFM_Guide_Engine_v1_0_0_FMPRESETMODEFB_ANALOG_INPUT 1


#define __S2_AMFM_Guide_Engine_v1_0_0_GUIDEREQUEST$_BUFFER_INPUT 2
#define __S2_AMFM_Guide_Engine_v1_0_0_GUIDEREQUEST$_BUFFER_MAX_LEN 255
CREATE_STRING_STRUCT( S2_AMFM_Guide_Engine_v1_0_0, __GUIDEREQUEST$, __S2_AMFM_Guide_Engine_v1_0_0_GUIDEREQUEST$_BUFFER_MAX_LEN );

#define __S2_AMFM_Guide_Engine_v1_0_0_AMPRESETIN_ANALOG_INPUT 3
#define __S2_AMFM_Guide_Engine_v1_0_0_AMPRESETIN_ARRAY_LENGTH 20
#define __S2_AMFM_Guide_Engine_v1_0_0_FMPRESETIN_ANALOG_INPUT 23
#define __S2_AMFM_Guide_Engine_v1_0_0_FMPRESETIN_ARRAY_LENGTH 20

/*
* DIGITAL_OUTPUT
*/
#define __S2_AMFM_Guide_Engine_v1_0_0_AMPRESETSAVEOUT_DIG_OUTPUT 0
#define __S2_AMFM_Guide_Engine_v1_0_0_FMPRESETSAVEOUT_DIG_OUTPUT 1

#define __S2_AMFM_Guide_Engine_v1_0_0_AMPRESETFB_DIG_OUTPUT 2
#define __S2_AMFM_Guide_Engine_v1_0_0_AMPRESETFB_ARRAY_LENGTH 20
#define __S2_AMFM_Guide_Engine_v1_0_0_FMPRESETFB_DIG_OUTPUT 22
#define __S2_AMFM_Guide_Engine_v1_0_0_FMPRESETFB_ARRAY_LENGTH 20

/*
* ANALOG_OUTPUT
*/
#define __S2_AMFM_Guide_Engine_v1_0_0_NEWAMCHANNEL_ANALOG_OUTPUT 0
#define __S2_AMFM_Guide_Engine_v1_0_0_NEWFMCHANNEL_ANALOG_OUTPUT 1
#define __S2_AMFM_Guide_Engine_v1_0_0_AMPRESETMODEOUT_ANALOG_OUTPUT 2
#define __S2_AMFM_Guide_Engine_v1_0_0_FMPRESETMODEOUT_ANALOG_OUTPUT 3

#define __S2_AMFM_Guide_Engine_v1_0_0_GUIDERESPONSE$_STRING_OUTPUT 4


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_AMFM_Guide_Engine_v1_0_0 )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __AMPRESETFB );
   DECLARE_IO_ARRAY( __FMPRESETFB );
   DECLARE_IO_ARRAY( __AMPRESETIN );
   DECLARE_IO_ARRAY( __FMPRESETIN );
   unsigned short __SEMAPHORE;
   unsigned short __SEMAPHORE2;
   unsigned short __AMPRESETTOSAVE;
   unsigned short __FMPRESETTOSAVE;
   unsigned short __REQUESTIDSAVINGAMPRESET;
   unsigned short __REQUESTIDSAVINGFMPRESET;
   unsigned short __AMPRESETSAVETYPE;
   unsigned short __FMPRESETSAVETYPE;
   DECLARE_STRING_STRUCT( S2_AMFM_Guide_Engine_v1_0_0, __GUIDEREQUEST$ );
};

START_NVRAM_VAR_STRUCT( S2_AMFM_Guide_Engine_v1_0_0 )
{
};



#endif //__S2_AMFM_GUIDE_ENGINE_V1_0_0_H__

