#ifndef __S2_XBMC_H__
#define __S2_XBMC_H__


#include "S2_Common_Functions.h"


/*
* Constructor and Destructor
*/

/*
* DIGITAL_INPUT
*/
#define __S2_XBMC_PLAYNEXT_DIG_INPUT 0
#define __S2_XBMC_PLAYPREV_DIG_INPUT 1
#define __S2_XBMC_UPDATEMOVIES_DIG_INPUT 2
#define __S2_XBMC_UPDATEMUSIC_DIG_INPUT 3
#define __S2_XBMC_JUMPFWD_SM_DIG_INPUT 4
#define __S2_XBMC_JUMPBACK_SM_DIG_INPUT 5
#define __S2_XBMC_JUMPFWD_LG_DIG_INPUT 6
#define __S2_XBMC_JUMPBACK_LG_DIG_INPUT 7
#define __S2_XBMC_ISPLAYINGONEXTERNALPLAYER_DIG_INPUT 8
#define __S2_XBMC_CHECKCURRENTLYPLAYING_DIG_INPUT 9
#define __S2_XBMC_GET_TIME_DIG_INPUT 10
#define __S2_XBMC_CLEARCURRENTLYPLAYING_DIG_INPUT 11
#define __S2_XBMC_ISCONNECTED_DIG_INPUT 12
#define __S2_XBMC_SOCKETISBUSY_DIG_INPUT 13


/*
* ANALOG_INPUT
*/
#define __S2_XBMC_SEEK_PERCENTAGE_ANALOG_INPUT 0
#define __S2_XBMC_SEEK_TIME_ANALOG_INPUT 1


#define __S2_XBMC_RX$_BUFFER_INPUT 2
#define __S2_XBMC_RX$_BUFFER_MAX_LEN 40000
CREATE_STRING_STRUCT( S2_XBMC, __RX$, __S2_XBMC_RX$_BUFFER_MAX_LEN );


/*
* DIGITAL_OUTPUT
*/
#define __S2_XBMC_PLAYFB_DIG_OUTPUT 0
#define __S2_XBMC_STOPFB_DIG_OUTPUT 1
#define __S2_XBMC_PAUSEFB_DIG_OUTPUT 2


/*
* ANALOG_OUTPUT
*/
#define __S2_XBMC_POSITION_SECONDS_ANALOG_OUTPUT 34
#define __S2_XBMC_DURATION_SECONDS_ANALOG_OUTPUT 35
#define __S2_XBMC_PROGRESS_PERCENTAGE_ANALOG_OUTPUT 36
#define __S2_XBMC_CURRENTLY_PLAYING_TYPE_ANALOG_OUTPUT 37

#define __S2_XBMC_CURRENTFILENAME$_STRING_OUTPUT 0
#define __S2_XBMC_CURRENTTITLE$_STRING_OUTPUT 1
#define __S2_XBMC_CURRENTCOVERART$_STRING_OUTPUT 2
#define __S2_XBMC_CURRENTCOVERARTJPEG$_STRING_OUTPUT 3
#define __S2_XBMC_CURRENTTIME$_STRING_OUTPUT 4
#define __S2_XBMC_CURRENTDURATION$_STRING_OUTPUT 5
#define __S2_XBMC_CURRENTPERCENTAGE$_STRING_OUTPUT 6
#define __S2_XBMC_CURRENTGENRE$_STRING_OUTPUT 7
#define __S2_XBMC_CURRENTSTUDIO$_STRING_OUTPUT 8
#define __S2_XBMC_CURRENTDIRECTOR$_STRING_OUTPUT 9
#define __S2_XBMC_CURRENTWRITER$_STRING_OUTPUT 10
#define __S2_XBMC_CURRENTTAGLINE$_STRING_OUTPUT 11
#define __S2_XBMC_CURRENTRATING$_STRING_OUTPUT 12
#define __S2_XBMC_CURRENTYEAR$_STRING_OUTPUT 13
#define __S2_XBMC_CURRENTSHOWTITLE$_STRING_OUTPUT 14
#define __S2_XBMC_CURRENTSEASON$_STRING_OUTPUT 15
#define __S2_XBMC_CURRENTEPISODE$_STRING_OUTPUT 16
#define __S2_XBMC_CURRENTFIRSTAIRED$_STRING_OUTPUT 17
#define __S2_XBMC_CURRENTPLOT$_STRING_OUTPUT 18
#define __S2_XBMC_CURRENTTRACKNUMBER$_STRING_OUTPUT 19
#define __S2_XBMC_CURRENTARTIST$_STRING_OUTPUT 20
#define __S2_XBMC_CURRENTALBUM$_STRING_OUTPUT 21
#define __S2_XBMC_CURRENTAUDIOBITRATE$_STRING_OUTPUT 22
#define __S2_XBMC_AUDIOCODEC$_STRING_OUTPUT 23
#define __S2_XBMC_VIDEOCODEC$_STRING_OUTPUT 24
#define __S2_XBMC_NEXTTITLE$_STRING_OUTPUT 25
#define __S2_XBMC_NEXTARTIST$_STRING_OUTPUT 26
#define __S2_XBMC_NEXTGENRE$_STRING_OUTPUT 27
#define __S2_XBMC_NEXTALBUM$_STRING_OUTPUT 28
#define __S2_XBMC_NEXTTRACKNUMBER$_STRING_OUTPUT 29
#define __S2_XBMC_PLAYSTATUS$_STRING_OUTPUT 30
#define __S2_XBMC_PLAYINGSPEED$_STRING_OUTPUT 31
#define __S2_XBMC_IPADDRESS$_STRING_OUTPUT 32
#define __S2_XBMC_TX$_STRING_OUTPUT 33


/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
#define __S2_XBMC_USEJPGEXTENSION_INTEGER_PARAMETER 12
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/
#define __S2_XBMC_XBMC_IPADDR$_STRING_PARAMETER 10
#define __S2_XBMC_XBMC_PORT$_STRING_PARAMETER 11
#define __S2_XBMC_LOGIN_STRING_PARAMETER 13
#define __S2_XBMC_PASSWORD_STRING_PARAMETER 14
#define __S2_XBMC_XBMC_IPADDR$_PARAM_MAX_LEN 16
CREATE_STRING_STRUCT( S2_XBMC, __XBMC_IPADDR$, __S2_XBMC_XBMC_IPADDR$_PARAM_MAX_LEN );
#define __S2_XBMC_XBMC_PORT$_PARAM_MAX_LEN 5
CREATE_STRING_STRUCT( S2_XBMC, __XBMC_PORT$, __S2_XBMC_XBMC_PORT$_PARAM_MAX_LEN );
#define __S2_XBMC_LOGIN_PARAM_MAX_LEN 30
CREATE_STRING_STRUCT( S2_XBMC, __LOGIN, __S2_XBMC_LOGIN_PARAM_MAX_LEN );
#define __S2_XBMC_PASSWORD_PARAM_MAX_LEN 30
CREATE_STRING_STRUCT( S2_XBMC, __PASSWORD, __S2_XBMC_PASSWORD_PARAM_MAX_LEN );


/*
* INTEGER
*/
CREATE_INTARRAY1D( S2_XBMC, __LIST_IDS, 10 );;
CREATE_INTARRAY1D( S2_XBMC, __SEASONNUMBER, 10 );;
CREATE_INTARRAY1D( S2_XBMC, __PLAYLISTIDS, 100 );;


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_XBMC_COVERARTINTERNAL$_STRING_MAX_LEN 512
CREATE_STRING_STRUCT( S2_XBMC, __COVERARTINTERNAL$, __S2_XBMC_COVERARTINTERNAL$_STRING_MAX_LEN );
#define __S2_XBMC_LIST_FILENAME$_ARRAY_NUM_ELEMS 10
#define __S2_XBMC_LIST_FILENAME$_ARRAY_NUM_CHARS 1024
CREATE_STRING_ARRAY( S2_XBMC, __LIST_FILENAME$, __S2_XBMC_LIST_FILENAME$_ARRAY_NUM_ELEMS, __S2_XBMC_LIST_FILENAME$_ARRAY_NUM_CHARS );
#define __S2_XBMC_LIST_PLOT$_ARRAY_NUM_ELEMS 10
#define __S2_XBMC_LIST_PLOT$_ARRAY_NUM_CHARS 1024
CREATE_STRING_ARRAY( S2_XBMC, __LIST_PLOT$, __S2_XBMC_LIST_PLOT$_ARRAY_NUM_ELEMS, __S2_XBMC_LIST_PLOT$_ARRAY_NUM_CHARS );
#define __S2_XBMC_RESULTNAME$_ARRAY_NUM_ELEMS 20
#define __S2_XBMC_RESULTNAME$_ARRAY_NUM_CHARS 40
CREATE_STRING_ARRAY( S2_XBMC, __RESULTNAME$, __S2_XBMC_RESULTNAME$_ARRAY_NUM_ELEMS, __S2_XBMC_RESULTNAME$_ARRAY_NUM_CHARS );
#define __S2_XBMC_RESULTVALUE$_ARRAY_NUM_ELEMS 20
#define __S2_XBMC_RESULTVALUE$_ARRAY_NUM_CHARS 2000
CREATE_STRING_ARRAY( S2_XBMC, __RESULTVALUE$, __S2_XBMC_RESULTVALUE$_ARRAY_NUM_ELEMS, __S2_XBMC_RESULTVALUE$_ARRAY_NUM_CHARS );

/*
* STRUCTURE
*/

START_GLOBAL_VAR_STRUCT( S2_XBMC )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   unsigned short __PLAYLISTPOSITION;
   unsigned short __ACTIVEPLAYER;
   unsigned short __LIST_PAGENUMBER;
   unsigned short __LIST_TOTAL;
   unsigned short __OLDSHOWLISTPAGE;
   unsigned short __OLDSEASONLISTPAGE;
   unsigned short __OLDARTISTLISTPAGE;
   unsigned short __OLDALBUMLISTPAGE;
   unsigned short __TVSHOWID;
   unsigned short __TVSHOWSEASONID;
   unsigned short __TVSHOWEPISODEID;
   unsigned short __ALBUMID;
   unsigned short __ARTISTID;
   unsigned short __TCPBLOCKER;
   unsigned short __ISTVSHOW;
   unsigned short __ISPLAYING;
   unsigned short __NAMEVALUECOUNT;
   DECLARE_INTARRAY( S2_XBMC, __LIST_IDS );
   DECLARE_INTARRAY( S2_XBMC, __SEASONNUMBER );
   DECLARE_INTARRAY( S2_XBMC, __PLAYLISTIDS );
   short __PLAYSPEED;
   DECLARE_STRING_STRUCT( S2_XBMC, __COVERARTINTERNAL$ );
   DECLARE_STRING_ARRAY( S2_XBMC, __LIST_FILENAME$ );
   DECLARE_STRING_ARRAY( S2_XBMC, __LIST_PLOT$ );
   DECLARE_STRING_ARRAY( S2_XBMC, __RESULTNAME$ );
   DECLARE_STRING_ARRAY( S2_XBMC, __RESULTVALUE$ );
   DECLARE_STRING_STRUCT( S2_XBMC, __RX$ );
   DECLARE_STRING_STRUCT( S2_XBMC, __XBMC_IPADDR$ );
   DECLARE_STRING_STRUCT( S2_XBMC, __XBMC_PORT$ );
   DECLARE_STRING_STRUCT( S2_XBMC, __LOGIN );
   DECLARE_STRING_STRUCT( S2_XBMC, __PASSWORD );
};

START_NVRAM_VAR_STRUCT( S2_XBMC )
{
};

DEFINE_WAITEVENT( S2_XBMC, __SPLS_TMPVAR__WAITLABEL_0__ );


#endif //__S2_XBMC_H__

